version: "3"

services:
  web:
    build: ./api
    ports:
      - "5000:5000"
    links:
      - redis
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
    volumes:
      - ./api:/app

  redis:
    container_name: redis
    image: redis:5.0.5
    hostname: redis
