version: "3"

services:
  web:
    build: ./api
    volumes:
      - ./api:/app/
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    stdin_open: true
    tty: true
    links:
      - redis
    depends_on:
      - redis

  redis:
    image: redis:latest

  worker:
    build:
      context: ./api
    hostname: worker
    entrypoint: celery
    command: -A celery_app.celery worker --loglevel=info
    volumes:
      - ./api:/app
    environment:
      - FLASK_DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    links:
      - redis
    depends_on:
      - web
      - redis
